//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.21 at 06:23:07 PM CEST 
//


package com.karim.foo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bidule" type="{http://www.w3.org/2001/XMLSchema}double" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *         &lt;element name="bar" type="{http://www.karim.com/foo}truc" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bidule",
    "bar"
})
@XmlRootElement(name = "foo")
public class Foo {

    @XmlElement(type = Double.class)
    protected List<Double> bidule;
    protected List<Truc> bar;

    /**
     * Gets the value of the bidule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bidule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBidule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getBidule() {
        if (bidule == null) {
            bidule = new ArrayList<Double>();
        }
        return this.bidule;
    }

    /**
     * Gets the value of the bar property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bar property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBar().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Truc }
     * 
     * 
     */
    public List<Truc> getBar() {
        if (bar == null) {
            bar = new ArrayList<Truc>();
        }
        return this.bar;
    }

}
